services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: modulo3-kafka
    hostname: modulo3-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://modulo3-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@modulo3-kafka:29093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data

    networks:
      - kafka-net

  modulo3-lambda:
    build:
      context: .
    container_name: modulo3-lambda
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: modulo3-kafka:29092
      KAFKA_TOPIC: citizen-topic
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
