spring:
  application:
    name: modulo3-lambda

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:modulo3-kafka:29092}
    consumer:
      group-id: modulo3-lambda-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: batch

app:
  kafka:
    topic-name: ${KAFKA_TOPIC:citizen-topic}
